import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    brand:null,
    nosize:null,
    hadsize:{cup:"",num:""},
    chestmeasure:{tuqi:"",xiqi:""},
    chestshapes:{shape:"",wk:""},
    cupfit:null,
    fitbar:null,
    furu:null,
    jixiong:null,
    backfit:null,
    upchestmeasure:null,
    prevurl:null
    //prevurltype:null
  },
  mutations: {
    selectbrand(state,value){
      state.brand=value
    },
    selectnosize(state,value){
      state.nosize=value
    },
    selecthadsize(state,value){
      state.hadsize=value
    },
    selectchestmeasure(state,value){
      state.chestmeasure=value
    },
    selectchestshapes(state,value){
      state.chestshapes=value
    },
    selectcupfit(state,value){
      state.cupfit=value
    },
    selectfitbar(state,value){
      state.fitbar=value
    },
    selectfuru(state,value){
      state.furu=value
    },
    selectjixiong(state,value){
      state.jixiong=value
    },
    selectbackfit(state,value){
      state.backfit=value
    },
    selectupchestmeasure(state,value){
      state.upchestmeasure=value
    },
    selectprevurl(state,value){
      state.prevurl=value
    }
  },
  actions: {
    commitbrand(context,value){
      context.commit('selectbrand',value)
    },
    commitnosize(context,value){
      context.commit('selectnosize',value)
    },
    commithadsize(context,value){
      context.commit('selecthadsize',value)
    },
    commitchestmeasure(context,value){
      context.commit('selectchestmeasure',value)
    },
    commitchestshapes(context,value){
      context.commit('selectchestshapes',value)
    },
    commitfitbar(context,value){
      context.commit('selectfitbar',value)
    },
    commitcupfit(context,value){
      context.commit('selectcupfit',value)
    },
    commitfuru(context,value){
      context.commit('selectfuru',value)
    },
    commitjixiong(context,value){
      context.commit('selectjixiong',value)
    },
    commitbackfit(context,value){
      context.commit('selectbackfit',value)
    },
    commitupchestmeasure(context,value){
      context.commit('selectupchestmeasure',value)
    },
    commitprevurl(context,value){
      context.commit('selectprevurl',value)
    }
  },
  modules: {
  }
})
